### ISSUE TITLE
Could not find End of Central Directory Record

### ISSUE THREAD

**Issue by tudosxxx** [brendan-duncan/archive#163]
where is error?

**Comment by brendan-duncan** [comment]
This usually means it's not a valid zip file.

**Comment by tudosxxx** [comment]
why? I can use it on windows.

**Comment by brendan-duncan** [comment]
No idea, you didn't provide any information other than the error message.

**Comment by tudosxxx** [comment]
`
 if(!File(zipPath).existsSync()){
      print('====unzip->>=noZipPath===$zipPath=========');
      return 0;
    }
    print(zipPath);
    print(savePath);
    try {
      final bytes = File(zipPath).readAsBytesSync();
      final archive = ZipDecoder().decodeBytes(bytes);
      print('========3========');
      for (final file in archive) {...
`

**Comment by tudosxxx** [comment]
this     final archive = ZipDecoder().decodeBytes(bytes); 

Could not find End of Central Directory Record

**Comment by tudosxxx** [comment]
I open the mobile phone directory, I can find the zip, and I can decompress the zip with commands

**Comment by brendan-duncan** [comment]
Thanks for the details. I'm still not sure, without analyzing the zip. There's something about it the library doesn't like. Possibly some newer variant of zip that this library isn't handled. If you have an example, I could take a look at it, otherwise I'm not sure.

The zip decoder starts at the end of the file then searches backward for the central directory signature, 0x06054b50. This is the structure that has the info about what files are in the zip. If it can't find it, it throws the error. I have no idea why it wouldn't be able to find it in your zip.

**Comment by tudosxxx** [comment]
[image.zip](https://github.com/brendan-duncan/archive/files/7207599/image.zip)

**Comment by brendan-duncan** [comment]
Strange. I was able to open it when I added it to the unit tests without any issues. 
```
final zip = ZipDecoder().decodeBytes(File(p.join(testDirPath, 'res/image.zip')).readAsBytesSync());
expect(zip.length, equals(7));
```

**Comment by tudosxxx** [comment]
Oh, maybe I copied it once and something went wrong。
`
var bytes = await rootBundle.load("assets/image.zip");
      String resFile = '${util.dirpath}/image.zip';
final buffer = bytes.buffer;
      //创建file路径
      File(resFile).writeAsBytes(buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes));
`

**Comment by tudosxxx** [comment]
But after I copied it, I used the windows command to view the phone directory and unzipped it.I try it again，thanks
