### ISSUE TITLE
The license is not recognized by Flutter

### ISSUE THREAD

**Issue by daviddgl** [brendan-duncan/archive#164]
We're using https://licensebat.com/ to check that all the packages we use have a valid license.
This one has one but it doesn't detect it as there are some issues with it.

<img width="1123" alt="Screenshot 2021-09-29 at 10 28 23" src="https://user-images.githubusercontent.com/11072221/135231973-5a34b537-bfbe-4188-92e0-f2bf8f0113b3.png">

**Comment by robertohuertasm** [comment]
Hi, probably the issue is that the license file is too imprecise. I mean, it starts as `Apache-2.0` but then it has segments from other kind of licenses. 

My guess is that `pub.dev` is unable to detect it properly the same way it happens for [Licensebat](https://licensebat) (disclaimer: I'm the author). 

Indeed, [Licensebat](https://licensebat) fallbacks to the license in the repo in case `pub.dev` fails to detect it and tries to match it against all known license texts. In this case, it detects it as [bzip2-1.0.6](https://spdx.org/licenses/bzip2-1.0.6.html) with a 59.22% score, precisely because it's embedded along with other texts in the license file.

Probably just avoiding the text of non Apache-2.0 licenses would be enough. Just mentioning that your work is based on libraries that use those other licenses should suffice: `zlib/inflate, zlib/deflate, bzip2`.

I've just tested it with a modified version of your license file and it detects `Apache-2.0` with more than a 90% score.
