### ISSUE TITLE
List<int> vs Uint8List 

### ISSUE THREAD

**Issue by lastant** [brendan-duncan/archive#55]
ZipDecoder.decodeBytes(...) expects `List<int>`. Is there a reason why you don't use Uint8List? It should consume less memory.

**Comment by brendan-duncan** [comment]
List<int> is a generic protocol, which uint8list implements. So, you can and should pass a uint8list to it.

**Comment by lastant** [comment]
I am using the library in a Flutter project and getting the data with a `MethodChannel` from the native code, which is sent as `byte[]` and received as UInt8List, according to the documentation: https://flutter.io/platform-channels/ . 
However, it works only if I do `.toList()` on the data first, otherwise the resulting `Archive` only contains some garbage..

**Comment by brendan-duncan** [comment]
That is interesting. It only ever uses uint8list internally, never a dart List. I can test to make sure, though I won’t be able to repo your exact usage.

**Comment by lastant** [comment]
Here is the basic code:

On the Dart side:

```
static const platform = const MethodChannel('channel');
platform.setMethodCallHandler((MethodCall call) async {
  if (call.method == 'chosen') {
    try {
      Archive archive = new ZipDecoder().decodeBytes(call.arguments);
    } on Exception catch (e) {
      print('Unable to open: ${e.toString()}');
    }
  }
});
await platform.invokeMethod('openDocument');
```

On the Java side:

```
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;

...

private static final String CHANNEL = "channel";
private static final int READ_REQUEST_CODE = 42;

private static MethodChannel channel;

protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  GeneratedPluginRegistrant.registerWith(this);

  channel = new MethodChannel(getFlutterView(), CHANNEL);
  channel.setMethodCallHandler(
    new MethodCallHandler() {
        @Override
        public void onMethodCall(MethodCall call, Result result) {
          if (call.method.equals("openDocument")) {
            Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
            intent.addCategory(Intent.CATEGORY_OPENABLE);
            intent.setType("application/zip");

            startActivityForResult(intent, READ_REQUEST_CODE);
            result.success(true);
          } else {
            result.notImplemented();
          }
        }
    }
  );
}

@Override
public void onActivityResult(int requestCode, int resultCode,
        Intent resultData) {
  if (requestCode == READ_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
    if (resultData != null) {
      final Uri uri = resultData.getData();

      try {
        InputStream inputStream = getContentResolver().openInputStream(uri);
        ByteArrayOutputStream byteBuffer = new ByteArrayOutputStream();
        int bufferSize = 1024;
        byte[] buffer = new byte[bufferSize];
        int len = 0;
        while ((len = inputStream.read(buffer)) != -1) {
          byteBuffer.write(buffer, 0, len);
        }

        channel.invokeMethod("chosen", byteBuffer.toByteArray());
      } catch (Exception e) {}
    }
  }
}
```

**Comment by lastant** [comment]
Actually, this is using an older version, 1.0.33. When I use the newest 2.0.3 and Flutter 0.5.8 and don't do .toList(), there is an exception: `FormatException: Bad UTF-8 encoding 0xf9 (at offset 1)`. The call stack:
```
_Utf8Decoder.convert (dart:convert/utf.dart:568)
Utf8Decoder.convert (dart:convert/utf.dart:344)
InputStream.readString (c:\Programs\flutter\.pub-cache\hosted\pub.dartlang.org\archive-2.0.3\lib\src\util\input_stream.dart:241)
new ZipFileHeader (c:\Programs\flutter\.pub-cache\hosted\pub.dartlang.org\archive-2.0.3\lib\src\zip\zip_file_header.dart:44)
new ZipDirectory.read (c:\Programs\flutter\.pub-cache\hosted\pub.dartlang.org\archive-2.0.3\lib\src\zip\zip_directory.dart:52)
ZipDecoder.decodeBuffer (c:\Programs\flutter\.pub-cache\hosted\pub.dartlang.org\archive-2.0.3\lib\src\zip_decoder.dart:21)
ZipDecoder.decodeBytes (c:\Programs\flutter\.pub-cache\hosted\pub.dartlang.org\archive-2.0.3\lib\src\zip_decoder.dart:17)
```
Here is the test file.

[book.zip](https://github.com/brendan-duncan/archive/files/2299961/book.zip)

**Comment by brendan-duncan** [comment]
File.readAsBytesSync also returns a Uint8List, which I verified with:
```
    var file = new File(p.join(testDirPath, 'book.zip'));
    var bytes = file.readAsBytesSync();
    print('!!!! isUint8List: ${bytes is Uint8List}');
    Archive archive = zipDecoder.decodeBytes(bytes, verify: true);
```
It prints true that bytes is a Uint8List, and the archive decoded correctly, with no Utf8 error or slow conversion to a list of int objects. Why would the bytes be different for you? I suspect when you pass the byteArray from Java to Dart, it's not really a Uint8List, or something else weird is going on. I don't have any experience with that, I haven't done anything with Flutter.

I acknowledge this is a really dumb suggestion, but you could try saving the bytes to a temp file and reading them from Dart like the above test...

**Comment by lastant** [comment]
Yes, reading a file from the Dart actually does work. When I compare the two data, they are identical, except that Java returns in fact a `_Uint8ArrayView`. Its `is ByteData` evaluates to false and `is List<int>` to true.

**Comment by brendan-duncan** [comment]
I'm a little confused. On the Java side, 
`channel.invokeMethod("chosen", byteBuffer.toByteArray());`
byteBuffer.toByteArray() returns a byte[], and according to the Flutter docs, MethodChannel.invokeMethod should translate create a Uint8List (I would imagine a Uint8List.view pointing to the raw data of the Java byte[]) to expose that data to Dart. A Uint8List.view is just a Uint8List that points to another ByteBuffer but doesn't own that data.  Maybe your last comment is just mixing up languages (I wish Dart had used the same typed_data class names that Java and Javascript use, ie Uint8Array and ByteData) instead of Uint8List and ByteBuffer...

On the Dart side of your project, I'm curious what happens if you do something like:
platform.setMethodCallHandler((MethodCall call) async {
  if (call.method == 'chosen') {
    try {
      var bytes = call.arguments;
      print('Bytes is Uint8List: ${bytes is Uint8List}');
      Archive archive = new ZipDecoder().decodeBytes(bytes as Uint8List);
    } on Exception catch (e) {
      print('Unable to open: ${e.toString()}');
    }
  }
});

If I were to guess what the problem is based on what's been said:
If bytes is reported to be a Uint8List, and the data is the same as if it were read from a file, and converting it to a list works but using bytes directly doesn't...what I suspect might be happening is garbage collection is deleting the backing byte buffer from the Java side, leaving the Dart Uint8List.view pointing to a backing ByteBuffer that no longer exists...

**Comment by lastant** [comment]
I mean Dart receives a `_Uint8ArrayView` from Java. Yes, I tried casting it, but the result is the same, and in the debugger it still shows up as a `_Uint8ArrayView`, and the IDE marks it as an 'Unnecessary cast'. It works if I do `Uint8List.fromList(bytes)`, but it's probably the same as calling `.toList()`. 
When digging deeper, I see that the call to `InputStream.toUint8List()` returns different results, and this is because `new Uint8List.view(b.buffer, offset, len)` returns different results. See the screenshots. First is when loading the file with Dart. Second when loading with Java.

![dartfile](https://user-images.githubusercontent.com/1300156/44354637-fd222a80-a46f-11e8-8d11-7fa5875acd34.png)
![javafile](https://user-images.githubusercontent.com/1300156/44354645-03b0a200-a470-11e8-99ff-147731012bdb.png)

**Comment by brendan-duncan** [comment]
I see, thanks for the screen shots. I still think this is a Flutter bug, but when I get a chance, I'll install Flutter and try and re-create the issue.

**Comment by lastant** [comment]
Yes, it's most likely a Flutter bug: `Uint8List.view()` simply returns a wrong value. Maybe I should file an issue. But could you think of some workaround? Maybe you could avoid this function in your code?

**Comment by brendan-duncan** [comment]
I can't think of any way to not use Uint8List.view. I'll see if I can find a workaround for this case, since it's the only broken case. And if we can identify what the actual issue is, it should definitely be reported to the Dart people. I know John Mccutchan and others there have hit similar issues with Uint8List before, when he was working on the Observatory, but it's been a while since I was doing any  Dart development work so I'm not sure who's working on what anymore.

**Comment by lastant** [comment]
But the direct access `buffer[offset++]` does work. Maybe it's possible to use it exclusively?

**Comment by brendan-duncan** [comment]
I wonder...
Since the data coming in from Java is a Uint8ArrayView, if it has a non-zero byte offset. I think the bug is in the creation of the new Uint8List.view in the toUint8List() method. It should be done as:
`Uint8List bytes = new Uint8List.view(b.buffer, b.offsetInBytes + offset, len);`
to maintain the original byte offset.

So, the new toUint8List() method would be:
```
Uint8List toUint8List() {
    int len = length;
    if (buffer is Uint8List) {
      Uint8List b = buffer;
      if ((offset + len) > b.length) {
        len = b.length - offset;
      }
      Uint8List bytes = new Uint8List.view(b.buffer, b.offsetInBytes + offset, len);
      return bytes;
    }
    int end = offset + len;
    if (end > buffer.length) {
      end = buffer.length;
    }
    return new Uint8List.fromList(buffer.sublist(offset, end));
  }
```

I'll make sure I don't break anything, push the change, and try and get Flutter set up on my machine to actually test it (easier said than done since time at home to work on it is mostly taken up by the kids.)

**Comment by brendan-duncan** [comment]
I pushed the update to git. Fingers crossed...

**Comment by brendan-duncan** [comment]
That change got pushed up in the 2.0.4 release.

**Comment by lastant** [comment]
Great, it works! Thanks so much!

**Comment by brendan-duncan** [comment]
I'm glad it was just my bug and not some fundamental issue with Dart. :-)

**Comment by lastant** [comment]
But why do you generally declare List<int> instead of Uint8List, for example here: https://github.com/brendan-duncan/archive/blob/209b93262428a72c09b91d5561a7ca6be85a378f/lib/src/util/output_stream.dart#L53

It seems Uint8List can be easily cast to List<int>, but the opposite is not true: need to do Uint8List.fromList(...) which is probably expensive. 
My problem is that the package epub, which uses archive under the hood, returns List<int> for images, but displaying them and storing with sqflite require Uint8List, and so I have to do this extra conversion.

**Comment by brendan-duncan** [comment]
The List<int> can be typecast to Uint8List without the fromList call:
var uint8List = list as Uint8List;

At the time I wrote this package, it was the early days of Dart, pre 1.0, and the language was changing on a regular basis. I agree I probably should have used the concrete class instead of the interface class throughout.  Maybe I can get to it one of these days. Of course I don't like to leave people with issues, so if the typecast doesn't work for you, I can look into it more.

**Comment by lastant** [comment]
No, I'm getting `type 'List<int>' is not a subtype of type 'Uint8List' in type cast` when doing this..

**Comment by lastant** [comment]
Btw, here is mentioned that `Uint8List` is preferred over `List<int>` because of slow conversion: https://github.com/tekartik/sqflite/blob/master/README.md

**Comment by brendan-duncan** [comment]
This may be a case where we're not fully understanding each other. I'll try an explain my understanding of List<int> and Uint8List, not to say you're not understanding it but just so we're on the same page. I also fully accept I may be totally off, and maybe (likely) there's something I'm not understanding.

In Dart, List<int> is an interface class, not an actual specific class. It's easy to confuse it with an array of number objects, such as 
`List<int> list = [1, 2, 3];`
because Dart only ever refers to that as a List<int>. But the array of number objects is an internal Dart class that implements the List<int> interface. Uint8List also implements the List<int> interface. As such,
the following works:
```
List<int> list = new Uint8List(5);
Uint8List uint8List = list as Uint8List;
```
But the following does not:
```
List<int> list = [1, 2, 3, 4, 5];
Uint8List uint8List = list as Uint8List; // This will fail
```

Everything the Archive library does internally is with Uint8List, and that is exposed externally via List<int> (a poor choice because it's confusing, but it is technically correct.)

I just tested the following and it does work:
```
OutputStream output = new OutputStream();
output.writeByte(42);
Uint8List bytes = output.getBytes() as Uint8List;
```

I suspect you're getting the cast error because a) what you're trying to cast is really an array of numbers and not an Uint8List; b) maybe there's some configuration I'm not aware of that's preventing it. The sqflite package recommends Uint8List over List<int> because I suspect they aren't typechecking the List<int> to see if it's actually a Uint8List; Archive library does typecheck lists and only converts if they are not a Uint8List.

**Comment by lastant** [comment]
I see. Then it's probably the code in the `epub` package that makes the data 'uncastable', maybe this one:
```
  List<int> openContentStream(ArchiveFile contentFileEntry) {
    List<int> contentStream = new List<int>();
    if (contentFileEntry.content == null)
      throw new Exception(
          'Incorrect EPUB file: content file \"${FileName}\" specified in manifest is not found.');
    contentStream.addAll(contentFileEntry.content);
    return contentStream;
  }
```

**Comment by brendan-duncan** [comment]
Creating an explicit `new List<int>` is creating an "array of number objects", which is the slow path.
Perhaps it should be:
```
Uint8List openContentStream(ArchiveFile contentFileEntry) {
    if (contentFileEntry.content == null)
      throw new Exception(
          'Incorrect EPUB file: content file \"${FileName}\" specified in manifest is not found.');
    return contentFileEntry.content as Uint8List;
  }
```
