### ISSUE TITLE
How to Unzip Password Files

### ISSUE THREAD

**Issue by jlcool** [brendan-duncan/archive#61]
How to Unzip Password Files
and
How to Compress a Password File

**Comment by brendan-duncan** [comment]
Sorry, it currently doesn't have zip password support.

**Comment by jlcool** [comment]
Please support it

**Comment by brendan-duncan** [comment]
I would love to if I could find some time to work on it. Hopefully I will, but unfortunately I can't make any promises that it will come soon.

**Comment by jlcool** [comment]
o(╥﹏╥)o

**Comment by brendan-duncan** [comment]
I just pushed an update to the git version of an attempt at decoding password zip files. I say "attempt" because I haven't had a chance to test it beyond my single trivial test case yet. If you're able to use the git version, you're welcome to test it:
`Archive archive = new ZipDecoder().decodeBytes(bytes, password: "mypassword");`
When I can find another chunk of free time, I'll test it more and publish it if it actually works like it should.

**Comment by brendan-duncan** [comment]
Closing the issue since as far as I know it should be working.
