### ISSUE TITLE
NoSuchMethodError: NoSuchMethodError: The method 'toUint8List' was called on null.

### ISSUE THREAD

**Issue by sidlatau** [brendan-duncan/archive#68]
Hi, thanks for the package. Archiving works well except one device - I pasted error below.
Package version: 2.0.8
Device: Huawei P20 EML-L29
Android version: 8.1

```
NoSuchMethodError: NoSuchMethodError: The method 'toUint8List' was called on null.
Receiver: null
Tried calling: toUint8List()
  File "input_file_stream.dart", line 288, in InputFileStream.toUint8List
  File "zip_encoder.dart", line 81, in ZipEncoder.getFileCrc32
  File "zip_encoder.dart", line 131, in ZipEncoder.addFile
  File "zip_file_encoder.dart", line 56, in ZipFileEncoder.addFile
  File "zip_file_encoder.dart", line 44, in ZipFileEncoder.addDirectory
  File "zip_file_encoder.dart", line 20, in ZipFileEncoder.zipDirectory
```

**Comment by brendan-duncan** [comment]
Interesting. I wish Dart had null language features like Swift, would make this type of code more stable.  I'll need to add a null check there, but trying to understand the fundamental issue of why it was null, my guess is it's an empty file, because it resets the read position of the file, then returns a null when the read occurs at the end of the stream. I can fix it to not fail on empty files, which it shouldn't crash, but if this file isn't supposed to be empty, then there might be some other issue too.

**Comment by brendan-duncan** [comment]
I pushed the fix (and unit test) for not crashing on empty files. I'll publish the fix shortly.

**Comment by sidlatau** [comment]
Tested code from `master` - can confirm that now archiving works. Thanks!
