### ISSUE TITLE
How to handle decompression of symbolic links?

### ISSUE THREAD

**Issue by cedx** [brendan-duncan/archive#71]
How can I properly decompress symbolic links contained in a TAR.GZ archive? The `FileArchive` API let us check if an entity is a file, but not if it is a symbolic link and its target path.
Is it possible? Did I miss an API?

**Comment by brendan-duncan** [comment]
There's not really a simple way of doing this now, but there should be. You might be able to do it with using TarDecoder directly. You'd use GzipDecoder to decompress the file first, then TarDecoder.decodeBytes with the decompressed buffer. Then, TarDecoder.files has a list of TarFile objects with Tar specific information about the files. TarFile.typeFlog would probably be TarFile.TYPE_SYMBOLIC_LINK if it's a symlink, and TarFile.nameOfLinkedFile would probably be the name of the file it's linked to. 

I'm saying "probably" because I'm not at a place where I can test to verify if I'm right or not.

ArchiveFile should really have symlink information available to it, so I'll work on that sometime soon.

**Comment by brendan-duncan** [comment]
I got a chance to check on this, and I was right, those properties of TarFile did have the symbolic link info.

I added some properties to ArchiveFile so you can get the symlink info from there:
class ArchiveFile { ...
  bool isSymbolicLink;
  String nameOfLinkedFile;
}

nameOfLinkedFile is the path of the file linked to, relative to the symlink file. 

The changes are in git, but not published yet.

**Comment by cedx** [comment]
Thanks a lot @brendan-duncan ! I don't have a specific requirement: I can wait without problem the next release of this library. In the meantime, I will try to test your solution as soon as I have spare time.

**Comment by brendan-duncan** [comment]
I published the change in version 2.0.9.

**Comment by cedx** [comment]
Great! I've tested the new release: it works as expected, so I'm closing this issue.
Another big thank you.

**Comment by sgehrman** [comment]
I have a zip file with a symlink, if I try and decompress it  with your lib, isSymbolicLink is false on that symlink.  Does this actually work?
