### ISSUE TITLE
Cannot unzip password protected archives

### ISSUE THREAD

**Issue by wenchangyiyo** [brendan-duncan/archive#83]
I'm trying to unzip a password protected archive but always get the message as below:

> [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: RangeError: Value not in range: -12

The code I used is very simple:
`
Future unzip(filePath, baseName) async{
    List<int> bytes = File("${filePath}/${baseName}").readAsBytesSync();
    // Decode the Zip file
    Archive archive = ZipDecoder().decodeBytes(bytes, verify:true, password: "1qaz2wsx");
    for (ArchiveFile file in archive) {
      print("file:"+file.name);
      print("size:"+(file.size / 1024).ceil().toString()+"K");
      print(file.content.toString());
      if (file.isFile) {
        File outFile = new File('${filePath}/out/${file.name}');
        outFile = await outFile.create(recursive: true);
        await outFile.writeAsBytes(file.content);
      } else {
        Directory('${filePath}/out/${file.name}')
          ..create(recursive: true);
      }
    }
  }
`

Does somebody knows why?

PS:the password is correct because I can unzip it in my PC after I download it from my mobile.
PS2:If I download a no password archive and unzip it. It works well.

**Comment by emaame** [comment]
I have encountered the same error.

The reason is that `ZipFile` calls the unwanted `_decodeRawContent` when dealing with a directory. `Value not in range: -12` means that it reads 12 bytes despite `_rawContent.length == 0` and then call `_rawContent.toUint8List()`.

I don't know how is a correct process, but if I check `_rawContent.length` and don't decode it, the error had been disappeared.

```ZipFile.dart
  List<int> get content {
    if (_content == null) {
      if (_rawContent.length <= 0) {
        _content = _rawContent.toUint8List();
        return _content;
      }
      if (_isEncrypted) {
        _rawContent = _decodeRawContent(_rawContent);
        _isEncrypted = false;
      }
```

I've attached an example ZIP file that reproduces the same error.
The encryption key is 1234.
[dummy.zip](https://github.com/brendan-duncan/archive/files/4428785/dummy.zip)

**Comment by ahmadkhedr** [comment]
> ```dart
> List<int> get content {
> ```

this worked but like this
```
if (_isEncrypted) {
        if(_rawContent.length <= 0){
          _content = _rawContent.toUint8List();
          _isEncrypted = false;
        }else{
          _rawContent = _decodeRawContent(_rawContent);
          _isEncrypted = false;
        }

      }
```
